apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-0bbc28d30247349f7
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeName: ebs-static-pv
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-static-pod
  labels:
    topic: volumes
    provisioner: static
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1d
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: ebs-static-vol
          mountPath: /usr/share/nginx/html
  volumes:
    - name: ebs-static-vol
      persistentVolumeClaim:
        claimName:  ebs-static-pvc
---
apiVersion: v1
kind: Service
metadata: 
  name: ebs-static-pvc
  labels:
    topic: volumes
    provisioner: static
spec:
  type: LoadBalancer
  selector:
    topic: volumes
    provisioner: static
  ports:
    - port: 80
      targetPort: 80