apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-04757dfd31579e521
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-static-pod
  labels:
    topic: volumes
    provisioner: static
spec:
  # nodeSelector:
  #   topology.kubernetes.io/zone: us-east-1a
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: efs-static-vol
          mountPath: /usr/share/nginx/html
  volumes:
    - name: efs-static-vol
      persistentVolumeClaim:
        claimName:  efs-static-pvc
---
apiVersion: v1
kind: Service
metadata: 
  name: efs-static-pvc
  labels:
    topic: volumes
    provisioner: static
spec:
  type: LoadBalancer
  selector:
    topic: volumes
    provisioner: static
  ports:
    - port: 80
      targetPort: 80