apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-06e5bf5af39992b3b
  storageClassName: "" # must be empty for static provisioning

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: efs-static-pv
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-static-pod
  labels:
    topic: volumes
    provisioner: static
    type: efs
spec:
  # nodeSelector:
  #   topology.kubernetes.io/zone: us-east-1a
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: ebs-static-vol
          mountPath: /usr/share/nginx/html
  volumes:
    - name: ebs-static-vol
      persistentVolumeClaim:
        claimName:  ebs-static-pvc
---
apiVersion: v1
kind: Service
metadata: 
  name: efs-static-svc
  labels:
    topic: volumes
    provisioner: static
    type: efs
spec:
  type: LoadBalancer
  selector:
    topic: volumes
    provisioner: static
  ports:
    - port: 80
      targetPort: 80
