
apiVersion: v1
kind: Pod
metadata:
  name: efs-dynamic-pod
  labels:
    topic: volumes
    provisioner: dynamic
    type: efs
spec:
  # nodeSelector:
  #   topology.kubernetes.io/zone: us-east-1a
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: efs-dynamic-vol
          mountPath: /usr/share/nginx/html
  volumes:
    - name: efs-dynamic-vol
      persistentVolumeClaim:
        claimName:  efs-dynamic-pvc
---
apiVersion: v1
kind: Service
metadata: 
  name: efs-dynamic-svc
  labels:
    topic: volumes
    provisioner: dynamic
    type: efs
spec:
  type: LoadBalancer
  selector:
    topic: volumes
    provisioner: dynamic
  ports:
    - port: 80
      targetPort: 80