apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-claim
  labels:
    topic: volumes
    provision: dynamic
spec:
  # nodeSelector:
  #   topology.kubernetes.io/zone: us-east-1d
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: ebs-dynamic-vol
          mountPath: /usr/share/nginx/html
  volumes:
    - name: ebs-dynamic-vol
      persistentVolumeClaim:
        claimName: ebs-dynamic-claim

---
apiVersion: v1
kind: Service
metadata:
  name: volume-claim-svc
spec:
  type: LoadBalancer
  selector:
    topic: volumes
    provision: dynamic
  ports:
    - port: 80
      targetPort: 80
