kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-07360c676ff7d2840
  directoryPerms: "700"
  # gidRangeStart: "1000" # optional
  # gidRangeEnd: "2000" # optional
  basePath: "/expense" # optional
  # subPathPattern: "${.PVC.namespace}/${.PVC.name}" # optional
  # ensureUniqueDirectory: "true" # optional
  # reuseAccessPoint: "false" # optional

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-dynamic-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-claim
  labels:
    topic: volumes
    provision: dynamic
spec:
  # nodeSelector:
  #   topology.kubernetes.io/zone: us-east-1d
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: efs-dynamic-vol
          mountPath: /usr/share/nginx/html
  volumes:
    - name: efs-dynamic-vol
      persistentVolumeClaim:
        claimName: efs-dynamic-claim

---
apiVersion: v1
kind: Service
metadata:
  name: volume-claim-svc
spec:
  type: LoadBalancer
  selector:
    topic: volumes
    provision: dynamic
  ports:
    - port: 80
      targetPort: 80
